[settings]
experimental = true
idiomatic_version_file_enable_tools = [
  # "java", -- handled by twiddling env flags for jenv
  "go",
  "node",
  "python",
  "ruby",
  "rust",
  "swift",
]
jobs = 12

[settings.python]
compile = false

[tools]
"gem:git-bump" = "latest"
node = "latest"
ruby = "latest"

# Overmind example for microservices
# assumes a Procfile with services defined
# [tasks.overmind]
# description = "Run files.com stack from Procfile with Overmind"
# run = [
#   "overmind start",
#   "sleep 0.5",
#   "overmind connect",
# ]

# [tasks.overmind.env]
# OVERMIND_SHELL = "zsh"
# OVERMIND_TITLE = "files-com"
# OVERMIND_SHOW_TIMESTAMPS = "true"
# OVERMIND_AUTO_RESTART = "all"
# OVERMIND_DAEMONIZE = "true"
# OVERMIND_TMUX_CONFIG = ""
