SHELL = /usr/bin/env zsh
included := atuin base direnv git heroku kitty rg ruby vim zsh
data_dir = $(shell echo $${XDG_DATA_HOME:-${HOME}/.local/share}/dotfiles)
packages = $(data_dir)/packages
brew_install = $(data_dir)/Brewfile.lock.json
Brewfile = $(data_dir)/Brewfile
Brewfile.d = $(data_dir)/Brewfile.d
Gemfile = $(data_dir)/Gemfile
Gemfile.d = $(data_dir)/Gemfile.d
target = /Users/caleb

.PHONY: all
all: brew_install rectangle stow vim-plug

.PHONY: stow
stow: $(data_dir)/packages ~/.stow-global-ignore
	mkdir -p $(target)
	stow --adopt --verbose --target=$(target) $(shell cat $(packages))

.PHONY: brew_install
brew_install: $(brew_install)
$(brew_install): install-homebrew $(data_dir)/Brewfile
	brew bundle check --file=$(Brewfile)

.PHONY: install-homebrew
install-homebrew:
	@which brew || /bin/bash -c "$$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

.PHONY: Brewfile
Brewfile: $(data_dir)/Brewfile
$(Brewfile): $(data_dir)/Brewfile.d
	echo "# This file is generated by Makefile." >> $@
	echo "# Do not edit manually, and do not commit." >> $@
	for i in $(Brewfile.d)/*; do cat $$i; done >> $@

.PHONY: Brewfile.d
Brewfile.d: $(Brewfile.d)
$(Brewfile.d): $(data_dir)/packages
	mkdir -p $@
	while read -d ' ' linkTarget; do \
		if [ -f $$linkTarget/Brewfile ]; then \
			ln -s "$$(realpath "$$linkTarget/Brewfile")" "$@/$$linkTarget"; \
		fi; \
	done < $(packages)

.PHONY: Gemfile
Gemfile: $(data_dir)/Gemfile
$(Gemfile): $(data_dir)/Gemfile.d
	echo "# This file is generated by Makefile." >> $@
	echo "# Do not edit manually, and do not commit." >> $@
	echo "source 'https://rubygems.org'" > $@
	for i in $(Gemfile.d)/*; do cat $$i; done >> $@

.PHONY: Gemfile.d
Gemfile.d: $(Gemfile.d)
$(Gemfile.d): $(data_dir)/packages
	mkdir -p $@
	while read -d ' ' linkTarget; do \
		if [ -f $$linkTarget/Gemfile ]; then \
			ln -s "$$(realpath "$$linkTarget/Gemfile")" "$@/$$linkTarget"; \
		fi; \
	done < $(packages)

.PHONY: packages
packages: $(packages)
$(packages): $(data_dir)
	echo "$(included)" > $@

.PHONY: data_dir
data_dir: $(data_dir)
$(data_dir):
	mkdir -p $(data_dir)

.PHONY: vim-plug
vim-plug: ~/.vim/autoload/plug.vim ~/.vimrc.bundles
	nvim -u ~/.vimrc.bundles +PlugInstall +qall

~/.vim/autoload/plug.vim:
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

.PHONY: rectangle
rectangle: ~/Library/Preferences/com.knollsoft.Rectangle.plist
# Must be a hard link
~/Library/Preferences/com.knollsoft.Rectangle.plist:
	ln rectangle/Library/Preferences/com.knollsoft.Rectangle.plist $@

~/.stow-global-ignore:
	ln -s $(PWD)/.stow-global-ignore $@

.PHONY: clean
clean:
	if [[ -f "$(packages)" ]]; then \
		stow --verbose --delete --target=$(target) $(shell cat $(packages)); \
	fi
	rm -rf $(data_dir)
	rm -rf ~/.vim/autoload/plug.vim
	rm ~/Library/Preferences/com.knollsoft.Rectangle.plist
