[[env]]
GEM_HOME = "{{config_root}}/.gem/ruby/{{exec(command='cat .ruby-version')}}"
GEM_PATH = "{{env.GEM_HOME}}"

[[env]]
_.path = "{{env.GEM_HOME}}/bin"

[hooks]
enter = [
  "[ -d \"$GEM_HOME\" ] || mkdir -p \"$GEM_HOME\"",
]

[tasks.overmind]
description = "Run files.com stack from Procfile with Overmind"
run = [
  "overmind start",
  "sleep 0.5",
  "overmind connect",
]

[tasks.overmind.env]
OVERMIND_SHELL = "zsh"
OVERMIND_TITLE = "files-com"
OVERMIND_SHOW_TIMESTAMPS = "true"
OVERMIND_AUTO_RESTART = "all"
OVERMIND_DAEMONIZE = "true"
OVERMIND_TMUX_CONFIG = ""

[tasks.ruby-lsp]
run = "ruby-lsp"

[tasks.ruby-lsp.env]
BUNDLE_GEMFILE = "./gems_ruby_lsp.rb"
GEM_HOME = "{{config_root}}/.ruby-lsp/.gem/ruby/{{exec(command='cat .ruby-version')}}"
GEM_PATH = "{{env.GEM_HOME}}:{{config_root}}/.gem/ruby/{{exec(command='cat .ruby-version')}}"

[tools]
"github:spinel-coop/rv" = "latest"
